In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
v1 = np.array([1,2,3]) # 3 dimensional
v2 = np.array([4,5,6])

In [3]:
print(v1)
print(v2)

[1 2 3]
[4 5 6]


In [7]:
v_add = v1 + v2
v_sub = v1 - v2

In [8]:
print(v_add)
print(v_sub)

[5 7 9]
[-3 -3 -3]


In [9]:
scalar = 2
vScaled = scalar * v1

In [10]:
print(vScaled)

[2 4 6]


In [11]:
dotProduct = np.dot(v1,v2)

In [12]:
print(dotProduct)

32


In [14]:
magnitudeOfv1 = np.linalg.norm(v1)
print(magnitudeOfv1)

3.7416573867739413


In [15]:
A = np.array([[1,2,3],[4,5,6]])
print(A)

B = np.array([[7,8,9],[10,11,12],[13,14,15]])
print(B)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [17]:
C = np.array([[1,2,3],[4,5,6]])
matrixAdd = A+C
matrixSub = A-C

print(matrixAdd)
print(matrixSub)

[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]


In [19]:
matrixMult = np.dot(A,B)

print(matrixMult)

[[ 66  72  78]
 [156 171 186]]


In [21]:
transposeA = A.T

print(transposeA)

[[1 4]
 [2 5]
 [3 6]]


In [23]:
# Coefficient matrix A and constant vector b
A = np.array([[2, 3], [4, -1]])
b = np.array([5, 3])

# Solve the system A * x = b
x = np.linalg.solve(A, b)

print("Solution (x, y):", x)

Solution (x, y): [1. 1.]


Eigenvalue / Eigenvector : Provided there is a matrix a, there exists a scalar lambda and vector v such that the matrix times the vector = the scalar times that vector
- Eigenvectors - directions that dont change direction when a matrix acts on them
- Eigenvalues - tell you how much those directions get stretched or squished
   ● If eigenvalues are negative → system decays
   ● Positive → system grows
   ● Complex → oscillations

In [26]:
A = np.array([[2,1],[1,2]])
eigenvalues, eigenvectors = np.linalg.eig(A)

print(eigenvalues)
print(eigenvectors)

[3. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [27]:
# Define a matrix
A = np.array([[4, 7], [2, 6]])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

print("Inverse of A:\n", A_inv)

# Verify: A * A_inv should be the identity matrix (like [[1,0][0,1]])
identity = np.dot(A, A_inv)
print("A * A_inv:\n", identity)

Inverse of A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
A * A_inv:
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


Singular Value Decomposition (SVD) is a factorization of a matrix into three
matrices:
A=UΣV T
Where:
● U and V are orthogonal matrices,
● Σ is a diagonal matrix of singular values.

In [29]:
# Define a matrix
A = np.array([[1, 2], [3, 4], [5, 6]])
# Perform SVD
U, sigma, Vt = np.linalg.svd(A)
print("U matrix:\n", U)
print("Sigma values:", sigma)
print("V^T matrix:\n", Vt)

U matrix:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Sigma values: [9.52551809 0.51430058]
V^T matrix:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
